repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [ "--config", "qa/.flake8.cfg"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-secure-coding-standard
          - flake8-warnings
          - flake8-use-fstring
          - flake8-mock
          - flake8-django
          - flake8-django-migrations

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort
        args: [ "--settings", "qa/.isort.cfg" ]

  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.3.2
    hooks:
      - id: docstr-coverage
        args: [ "--config", "qa/.docstr.yaml" ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        args: [ "--ini", "qa/.bandit.ini" ]

  - repo: https://github.com/seddonym/import-linter
    rev: v2.9
    hooks:
      - id: import-linter
        args: [ "--config", "qa/.import-rules.ini" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        args: ["--config-file", "qa/.mypy.ini"]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"

  - repo: https://github.com/python-poetry/poetry
    rev: '2.2.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
